apiVersion : apps/v1
kind: Deployment
metadata:
  name: hemanthpipelinesjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hemanthpipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: hemanthpipelinesjavascriptdocker 
    spec:
      containers:
        - name: hemanthpipelinesjavascriptdocker 
          image: hemiacr.southeastasia.data.azurecr.io/hemanthpipelinesjavascriptdocker
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: hemanthpipelinesjavascriptdocker
spec:
    type: LoadBalancer
    ports:
    - port: 8080 
    selector:
        app: hemanthpipelinesjavascriptdocker
